### ISSUE TITLE
Create an account (artist)

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#20] opened 2019-03-29 05:53 UTC
As an artist, I want to create an account and profile (that I can edit from time to time).

**Comment by pgholsgrove** [comment] 2019-03-29 05:57
As an artist, I want to create an account on Zien, so I can upload new editions, manage my account and subscribe to other artist's channels

**Comment by zoenolan** [comment] 2019-06-23 11:59
Duplicate of https://github.com/axna/zien/issues/21

**Closed by zoenolan** 2019-06-23 11:59 UTC
